import type { User, Item, Match, Claim, Conversation, Message, Notification } from "./types"

export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "john@example.com",
    full_name: "John Doe",
    student_id: "STU12345",
    phone: "+1234567890",
    role: "user",
    reputation_score: 75,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
  },
  {
    id: "user-2",
    email: "jane@example.com",
    full_name: "Jane Smith",
    student_id: "STU12346",
    role: "user",
    reputation_score: 92,
    is_active: true,
    created_at: "2024-01-05T00:00:00Z",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
  },
  {
    id: "user-3",
    email: "mike@example.com",
    full_name: "Mike Johnson",
    role: "user",
    reputation_score: 45,
    is_active: true,
    created_at: "2024-02-10T00:00:00Z",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
  },
]

export const mockItems: Item[] = [
  {
    id: "item-1",
    type: "lost",
    title: "iPhone 15 Pro",
    description: "Black iPhone 15 Pro with a cracked screen protector. Lost near the main library entrance. Has a blue case with a card holder.",
    category: "Electronics",
    location: "Main Library, 2nd Floor",
    date_lost_found: "2024-01-15",
    status: "active",
    tags: ["iphone", "black", "library", "phone"],
    images: ["https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=300&fit=crop"],
    user_id: "user-1",
    user: mockUsers[0],
    created_at: "2024-01-15T10:30:00Z",
    updated_at: "2024-01-15T10:30:00Z",
  },
  {
    id: "item-2",
    type: "found",
    title: "MacBook Pro Charger",
    description: "Found a 96W MacBook Pro charger in the computer lab. White color, USB-C type.",
    category: "Electronics",
    location: "Computer Lab B",
    date_lost_found: "2024-01-16",
    status: "active",
    tags: ["macbook", "charger", "apple"],
    images: ["https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400&h=300&fit=crop"],
    user_id: "user-2",
    user: mockUsers[1],
    created_at: "2024-01-16T14:20:00Z",
    updated_at: "2024-01-16T14:20:00Z",
  },
  {
    id: "item-3",
    type: "lost",
    title: "Red Backpack",
    description: "Jansport red backpack with laptop compartment. Contains notebooks and a water bottle. Has a small tear on the front pocket.",
    category: "Bags",
    location: "Student Center Cafeteria",
    date_lost_found: "2024-01-14",
    status: "active",
    tags: ["backpack", "red", "jansport"],
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=300&fit=crop"],
    user_id: "user-3",
    user: mockUsers[2],
    created_at: "2024-01-14T09:00:00Z",
    updated_at: "2024-01-14T09:00:00Z",
  },
  {
    id: "item-4",
    type: "found",
    title: "Student ID Card",
    description: "Found a student ID card near the parking lot. Name partially visible.",
    category: "Documents",
    location: "Parking Lot A",
    date_lost_found: "2024-01-17",
    status: "claimed",
    tags: ["id", "card", "student"],
    images: ["https://images.unsplash.com/photo-1578670812003-60745e2c2ea9?w=400&h=300&fit=crop"],
    user_id: "user-2",
    user: mockUsers[1],
    created_at: "2024-01-17T11:45:00Z",
    updated_at: "2024-01-18T08:00:00Z",
  },
  {
    id: "item-5",
    type: "found",
    title: "Car Keys with Ford Logo",
    description: "Set of car keys with Ford key fob and 3 other keys. Found outside the gym.",
    category: "Keys",
    location: "Gymnasium Entrance",
    date_lost_found: "2024-01-18",
    status: "active",
    tags: ["keys", "ford", "car"],
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop"],
    user_id: "user-1",
    user: mockUsers[0],
    created_at: "2024-01-18T16:30:00Z",
    updated_at: "2024-01-18T16:30:00Z",
  },
  {
    id: "item-6",
    type: "lost",
    title: "Blue Wireless Earbuds",
    description: "Samsung Galaxy Buds in blue color. Lost somewhere between the library and science building.",
    category: "Electronics",
    location: "Science Building",
    date_lost_found: "2024-01-13",
    status: "active",
    tags: ["earbuds", "samsung", "blue", "wireless"],
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=300&fit=crop"],
    user_id: "user-2",
    user: mockUsers[1],
    created_at: "2024-01-13T13:15:00Z",
    updated_at: "2024-01-13T13:15:00Z",
  },
  {
    id: "item-7",
    type: "lost",
    title: "Leather Wallet",
    description: "Brown leather bifold wallet. Contains cards but no cash. Has initials 'MJ' embossed.",
    category: "Accessories",
    location: "Engineering Building",
    date_lost_found: "2024-01-19",
    status: "active",
    tags: ["wallet", "leather", "brown"],
    images: ["https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&h=300&fit=crop"],
    user_id: "user-3",
    user: mockUsers[2],
    created_at: "2024-01-19T08:45:00Z",
    updated_at: "2024-01-19T08:45:00Z",
  },
  {
    id: "item-8",
    type: "found",
    title: "Prescription Glasses",
    description: "Black frame prescription glasses found on a bench. Ray-Ban brand.",
    category: "Accessories",
    location: "Central Park Area",
    date_lost_found: "2024-01-20",
    status: "active",
    tags: ["glasses", "rayban", "prescription"],
    images: ["https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=400&h=300&fit=crop"],
    user_id: "user-1",
    user: mockUsers[0],
    created_at: "2024-01-20T12:00:00Z",
    updated_at: "2024-01-20T12:00:00Z",
  },
]

export const mockMatches: Match[] = [
  {
    id: "match-1",
    lost_item_id: "item-1",
    found_item_id: "item-2",
    similarity_score: 0.35,
    matching_attributes: ["category", "location_proximity"],
    lost_item: mockItems[0],
    found_item: mockItems[1],
    created_at: "2024-01-17T00:00:00Z",
  },
  {
    id: "match-2",
    lost_item_id: "item-6",
    found_item_id: "item-8",
    similarity_score: 0.42,
    matching_attributes: ["category"],
    lost_item: mockItems[5],
    found_item: mockItems[7],
    created_at: "2024-01-20T12:30:00Z",
  },
  {
    id: "match-3",
    lost_item_id: "item-7",
    found_item_id: "item-5",
    similarity_score: 0.28,
    matching_attributes: ["location_proximity"],
    lost_item: mockItems[6],
    found_item: mockItems[4],
    created_at: "2024-01-19T10:00:00Z",
  },
]

export const mockClaims: Claim[] = [
  {
    id: "claim-1",
    item_id: "item-4",
    claimer_id: "user-3",
    description: "This is my student ID card. I can verify with my student number.",
    verification_details: {
      student_number: "STU98765",
      date_of_birth: "1999-05-15",
    },
    status: "approved",
    item: mockItems[3],
    claimer: mockUsers[2],
    created_at: "2024-01-17T15:00:00Z",
  },
  {
    id: "claim-2",
    item_id: "item-5",
    claimer_id: "user-2",
    description: "These are my car keys. The Ford is a 2020 F-150 blue color.",
    verification_details: {
      car_model: "2020 Ford F-150",
      color: "Blue",
    },
    status: "pending",
    item: mockItems[4],
    claimer: mockUsers[1],
    created_at: "2024-01-19T09:00:00Z",
  },
  {
    id: "claim-3",
    item_id: "item-2",
    claimer_id: "user-3",
    description: "This is my MacBook charger. I have the matching MacBook Pro 16-inch.",
    verification_details: {
      laptop_model: "MacBook Pro 16-inch 2023",
      serial_hint: "C02...",
    },
    status: "pending",
    item: mockItems[1],
    claimer: mockUsers[2],
    created_at: "2024-01-18T10:30:00Z",
  },
]

export const mockConversations: Conversation[] = [
  {
    user: mockUsers[1],
    last_message: "Thanks for finding my charger! When can we meet?",
    last_message_at: "2024-01-18T16:30:00Z",
    unread_count: 2,
  },
  {
    user: mockUsers[2],
    last_message: "Is the backpack still available?",
    last_message_at: "2024-01-17T14:20:00Z",
    unread_count: 0,
  },
]

export const mockMessages: Record<string, Message[]> = {
  "user-2": [
    {
      id: "msg-1",
      sender_id: "user-2",
      receiver_id: "user-1",
      content: "Hi! I saw that you found a MacBook charger. Is it still available?",
      is_read: true,
      created_at: "2024-01-18T15:00:00Z",
    },
    {
      id: "msg-2",
      sender_id: "user-1",
      receiver_id: "user-2",
      content: "Yes, it is! Are you the owner?",
      is_read: true,
      created_at: "2024-01-18T15:05:00Z",
    },
    {
      id: "msg-3",
      sender_id: "user-2",
      receiver_id: "user-1",
      content: "I believe so. I lost mine in the computer lab yesterday.",
      is_read: true,
      created_at: "2024-01-18T15:10:00Z",
    },
    {
      id: "msg-4",
      sender_id: "user-2",
      receiver_id: "user-1",
      content: "Thanks for finding my charger! When can we meet?",
      is_read: false,
      created_at: "2024-01-18T16:30:00Z",
    },
  ],
  "user-3": [
    {
      id: "msg-5",
      sender_id: "user-3",
      receiver_id: "user-1",
      content: "Is the backpack still available?",
      is_read: true,
      created_at: "2024-01-17T14:20:00Z",
    },
  ],
}

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    type: "match_found",
    message: "New match found for your lost iPhone!",
    data: { match_id: "match-1", item_id: "item-1" },
    is_read: false,
    created_at: "2024-01-17T00:00:00Z",
  },
  {
    id: "notif-2",
    type: "claim_update",
    message: "Your claim on the student ID card has been approved!",
    data: { claim_id: "claim-1" },
    is_read: false,
    created_at: "2024-01-17T18:00:00Z",
  },
  {
    id: "notif-3",
    type: "message",
    message: "New message from Jane Smith",
    data: { user_id: "user-2" },
    is_read: true,
    created_at: "2024-01-18T16:30:00Z",
  },
  {
    id: "notif-4",
    type: "item_claimed",
    message: "Someone has claimed your found keys!",
    data: { item_id: "item-5", claim_id: "claim-2" },
    is_read: false,
    created_at: "2024-01-19T09:00:00Z",
  },
]

export const currentUser = mockUsers[0]
